### ISSUE TITLE
Unable to switch SElinux state

### ISSUE THREAD

**Issue by nirgranth** [MrBIMC/SELinuxModeChanger#12] opened 2020-07-06 19:55 UTC
I am unable to switch states help pls
![Screenshot_20200707-012353](https://user-images.githubusercontent.com/48947296/86635456-b81a2980-bff0-11ea-8780-ac0c46ed206c.png)
![Screenshot_20200707-012401](https://user-images.githubusercontent.com/48947296/86635462-ba7c8380-bff0-11ea-9cd5-cae9c5613908.png)

**Comment by codedfiles** [comment] 2021-07-13 01:35
Duplicate of #

**Comment by codedfiles** [comment] 2021-07-21 03:04
Duplicate of #

**Comment by codedfiles** [comment] 2021-07-21 03:04
app/src/main/java/com/mrbimc/selinux/MainActivity.kt

**Comment by ase12558** [comment] 2021-10-16 09:04
> I am unable to switch states help pls ![Screenshot_20200707-012353](https://user-images.githubusercontent.com/48947296/86635456-b81a2980-bff0-11ea-8780-ac0c46ed206c.png) ![Screenshot_20200707-012401](https://user-images.githubusercontent.com/48947296/86635462-ba7c8380-bff0-11ea-9cd5-cae9c5613908.png)

**Comment by ase12558** [comment] 2021-10-16 09:04
給

**Comment by ase12558** [comment] 2021-11-06 19:35
> 給

**Comment by ase12558** [comment] 2022-01-19 18:23
> I am unable to switch states help pls ![Screenshot_20200707-012353](https://user-images.githubusercontent.com/48947296/86635456-b81a2980-bff0-11ea-8780-ac0c46ed206c.png) ![Screenshot_20200707-012401](https://user-images.githubusercontent.com/48947296/86635462-ba7c8380-bff0-11ea-9cd5-cae9c5613908.png)

**Comment by nirgranth** [comment] 2022-04-11 20:08
> > 給

what to give?

**Closed as not planned** 2024-05-24 04:31 UTC
